apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-ecr-rotate-tokens.serviceAccount" . }}
  labels:
{{ include "aws-ecr-rotate-tokens.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "aws-ecr-rotate-tokens.serviceAccount" . }}
  labels:
{{ include "aws-ecr-rotate-tokens.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: {{ include "aws-ecr-rotate-tokens.serviceAccount" . }}
    namespace: {{ .Release.Namespace }}